# trigger:
# - master

schedules:
  - cron: "32 12 * * *"  # Runs daily at 12:00 PM UTC
    displayName: "Daily Scheduled Build"
    branches:
      include:
        - master
    always: true

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  displayName: 'Veracode SCA scan'
  inputs:
    targetType: 'inline'
    script: |
          export SRCCLR_API_TOKEN=$(SRCCLR)
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --recursive --update-advisor